'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CllLogicaNegocio.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_agregarlineadetalle.
        '''</summary>
        Friend ReadOnly Property proc_agregarlineadetalle() As String
            Get
                Return ResourceManager.GetString("proc_agregarlineadetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_agregarservicioagrupodeventa.
        '''</summary>
        Friend ReadOnly Property proc_agregarservicioagrupodeventa() As String
            Get
                Return ResourceManager.GetString("proc_agregarservicioagrupodeventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_agregarvendedoragrupodeventa.
        '''</summary>
        Friend ReadOnly Property proc_agregarvendedoragrupodeventa() As String
            Get
                Return ResourceManager.GetString("proc_agregarvendedoragrupodeventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_aprobarfactura.
        '''</summary>
        Friend ReadOnly Property proc_aprobarfactura() As String
            Get
                Return ResourceManager.GetString("proc_aprobarfactura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_asignarclienteusuario.
        '''</summary>
        Friend ReadOnly Property proc_asignarclienteusuario() As String
            Get
                Return ResourceManager.GetString("proc_asignarclienteusuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscardetalle.
        '''</summary>
        Friend ReadOnly Property proc_buscardetalle() As String
            Get
                Return ResourceManager.GetString("proc_buscardetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarfactura.
        '''</summary>
        Friend ReadOnly Property proc_buscarfactura() As String
            Get
                Return ResourceManager.GetString("proc_buscarfactura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarfacturaaprox.
        '''</summary>
        Friend ReadOnly Property proc_buscarfacturaaprox() As String
            Get
                Return ResourceManager.GetString("proc_buscarfacturaaprox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarfacturasgrupoventasporfechas.
        '''</summary>
        Friend ReadOnly Property proc_buscarfacturasgrupoventasporfechas() As String
            Get
                Return ResourceManager.GetString("proc_buscarfacturasgrupoventasporfechas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarfacturasporcliente.
        '''</summary>
        Friend ReadOnly Property proc_buscarfacturasporcliente() As String
            Get
                Return ResourceManager.GetString("proc_buscarfacturasporcliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarfacturasporfechas.
        '''</summary>
        Friend ReadOnly Property proc_buscarfacturasporfechas() As String
            Get
                Return ResourceManager.GetString("proc_buscarfacturasporfechas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarfacturasporvendedor.
        '''</summary>
        Friend ReadOnly Property proc_buscarfacturasporvendedor() As String
            Get
                Return ResourceManager.GetString("proc_buscarfacturasporvendedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscargrupodeventa.
        '''</summary>
        Friend ReadOnly Property proc_buscargrupodeventa() As String
            Get
                Return ResourceManager.GetString("proc_buscargrupodeventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscargrupodeventaaprox.
        '''</summary>
        Friend ReadOnly Property proc_buscargrupodeventaaprox() As String
            Get
                Return ResourceManager.GetString("proc_buscargrupodeventaaprox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarpermisosxrol.
        '''</summary>
        Friend ReadOnly Property proc_buscarpermisosxrol() As String
            Get
                Return ResourceManager.GetString("proc_buscarpermisosxrol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarserviciosdegrupoventas.
        '''</summary>
        Friend ReadOnly Property proc_buscarserviciosdegrupoventas() As String
            Get
                Return ResourceManager.GetString("proc_buscarserviciosdegrupoventas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarserviciosdispparagrupo.
        '''</summary>
        Friend ReadOnly Property proc_buscarserviciosdispparagrupo() As String
            Get
                Return ResourceManager.GetString("proc_buscarserviciosdispparagrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarusuarioaproxnombre.
        '''</summary>
        Friend ReadOnly Property proc_buscarusuarioaproxnombre() As String
            Get
                Return ResourceManager.GetString("proc_buscarusuarioaproxnombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarusuarioid.
        '''</summary>
        Friend ReadOnly Property proc_buscarusuarioid() As String
            Get
                Return ResourceManager.GetString("proc_buscarusuarioid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarusuarioporcorreoycontrasenna.
        '''</summary>
        Friend ReadOnly Property proc_buscarusuarioporcorreoycontrasenna() As String
            Get
                Return ResourceManager.GetString("proc_buscarusuarioporcorreoycontrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarvendedoresdegrupoventas.
        '''</summary>
        Friend ReadOnly Property proc_buscarvendedoresdegrupoventas() As String
            Get
                Return ResourceManager.GetString("proc_buscarvendedoresdegrupoventas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarvendedoresdispparagrupo.
        '''</summary>
        Friend ReadOnly Property proc_buscarvendedoresdispparagrupo() As String
            Get
                Return ResourceManager.GetString("proc_buscarvendedoresdispparagrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_cambiarcontrasenna.
        '''</summary>
        Friend ReadOnly Property proc_cambiarcontrasenna() As String
            Get
                Return ResourceManager.GetString("proc_cambiarcontrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_deletecliente.
        '''</summary>
        Friend ReadOnly Property proc_deletecliente() As String
            Get
                Return ResourceManager.GetString("proc_deletecliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_deleteplanventa.
        '''</summary>
        Friend ReadOnly Property proc_deleteplanventa() As String
            Get
                Return ResourceManager.GetString("proc_deleteplanventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_deleteservicio.
        '''</summary>
        Friend ReadOnly Property proc_deleteservicio() As String
            Get
                Return ResourceManager.GetString("proc_deleteservicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_eliminarfactura.
        '''</summary>
        Friend ReadOnly Property proc_eliminarfactura() As String
            Get
                Return ResourceManager.GetString("proc_eliminarfactura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_eliminargrupodeventa.
        '''</summary>
        Friend ReadOnly Property proc_eliminargrupodeventa() As String
            Get
                Return ResourceManager.GetString("proc_eliminargrupodeventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_eliminarlineadetalle.
        '''</summary>
        Friend ReadOnly Property proc_eliminarlineadetalle() As String
            Get
                Return ResourceManager.GetString("proc_eliminarlineadetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_eliminarserviciodegrupodeventa.
        '''</summary>
        Friend ReadOnly Property proc_eliminarserviciodegrupodeventa() As String
            Get
                Return ResourceManager.GetString("proc_eliminarserviciodegrupodeventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_eliminarusuario.
        '''</summary>
        Friend ReadOnly Property proc_eliminarusuario() As String
            Get
                Return ResourceManager.GetString("proc_eliminarusuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_eliminarvendedordegrupodeventa.
        '''</summary>
        Friend ReadOnly Property proc_eliminarvendedordegrupodeventa() As String
            Get
                Return ResourceManager.GetString("proc_eliminarvendedordegrupodeventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_extraerDatosComisionCalculada.
        '''</summary>
        Friend ReadOnly Property proc_extraerDatosComisionCalculada() As String
            Get
                Return ResourceManager.GetString("proc_extraerDatosComisionCalculada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_insertcliente.
        '''</summary>
        Friend ReadOnly Property proc_insertcliente() As String
            Get
                Return ResourceManager.GetString("proc_insertcliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_insertplanservicio.
        '''</summary>
        Friend ReadOnly Property proc_insertplanservicio() As String
            Get
                Return ResourceManager.GetString("proc_insertplanservicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_insertplanventa.
        '''</summary>
        Friend ReadOnly Property proc_insertplanventa() As String
            Get
                Return ResourceManager.GetString("proc_insertplanventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_insertservicio.
        '''</summary>
        Friend ReadOnly Property proc_insertservicio() As String
            Get
                Return ResourceManager.GetString("proc_insertservicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_invalidarfactura.
        '''</summary>
        Friend ReadOnly Property proc_invalidarfactura() As String
            Get
                Return ResourceManager.GetString("proc_invalidarfactura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarclientes.
        '''</summary>
        Friend ReadOnly Property proc_listarclientes() As String
            Get
                Return ResourceManager.GetString("proc_listarclientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarcomisionesporvendedor.
        '''</summary>
        Friend ReadOnly Property proc_listarcomisionesporvendedor() As String
            Get
                Return ResourceManager.GetString("proc_listarcomisionesporvendedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarfacturas.
        '''</summary>
        Friend ReadOnly Property proc_listarfacturas() As String
            Get
                Return ResourceManager.GetString("proc_listarfacturas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listargrupos.
        '''</summary>
        Friend ReadOnly Property proc_listargrupos() As String
            Get
                Return ResourceManager.GetString("proc_listargrupos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarpermisos.
        '''</summary>
        Friend ReadOnly Property proc_listarpermisos() As String
            Get
                Return ResourceManager.GetString("proc_listarpermisos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarplanes.
        '''</summary>
        Friend ReadOnly Property proc_listarplanes() As String
            Get
                Return ResourceManager.GetString("proc_listarplanes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarservicios.
        '''</summary>
        Friend ReadOnly Property proc_listarservicios() As String
            Get
                Return ResourceManager.GetString("proc_listarservicios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarusuarios.
        '''</summary>
        Friend ReadOnly Property proc_listarusuarios() As String
            Get
                Return ResourceManager.GetString("proc_listarusuarios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarvendedores.
        '''</summary>
        Friend ReadOnly Property proc_listarvendedores() As String
            Get
                Return ResourceManager.GetString("proc_listarvendedores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_modificargrupodeventa.
        '''</summary>
        Friend ReadOnly Property proc_modificargrupodeventa() As String
            Get
                Return ResourceManager.GetString("proc_modificargrupodeventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_modificarusuario.
        '''</summary>
        Friend ReadOnly Property proc_modificarusuario() As String
            Get
                Return ResourceManager.GetString("proc_modificarusuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_registrarfactura.
        '''</summary>
        Friend ReadOnly Property proc_registrarfactura() As String
            Get
                Return ResourceManager.GetString("proc_registrarfactura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_registrargrupodeventa.
        '''</summary>
        Friend ReadOnly Property proc_registrargrupodeventa() As String
            Get
                Return ResourceManager.GetString("proc_registrargrupodeventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_registrarusuario.
        '''</summary>
        Friend ReadOnly Property proc_registrarusuario() As String
            Get
                Return ResourceManager.GetString("proc_registrarusuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_registrarusuario.
        '''</summary>
        Friend ReadOnly Property proc_registrarusuario1() As String
            Get
                Return ResourceManager.GetString("proc_registrarusuario1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_SelectAllDepartamento.
        '''</summary>
        Friend ReadOnly Property proc_SelectAllDepartamento() As String
            Get
                Return ResourceManager.GetString("proc_SelectAllDepartamento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_SelectAllRol.
        '''</summary>
        Friend ReadOnly Property proc_SelectAllRol() As String
            Get
                Return ResourceManager.GetString("proc_SelectAllRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_selectclienteid.
        '''</summary>
        Friend ReadOnly Property proc_selectclienteid() As String
            Get
                Return ResourceManager.GetString("proc_selectclienteid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_selectclientenombre.
        '''</summary>
        Friend ReadOnly Property proc_selectclientenombre() As String
            Get
                Return ResourceManager.GetString("proc_selectclientenombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_selectplanservicio.
        '''</summary>
        Friend ReadOnly Property proc_selectplanservicio() As String
            Get
                Return ResourceManager.GetString("proc_selectplanservicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_selectplanventa.
        '''</summary>
        Friend ReadOnly Property proc_selectplanventa() As String
            Get
                Return ResourceManager.GetString("proc_selectplanventa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_selectserviciocod.
        '''</summary>
        Friend ReadOnly Property proc_selectserviciocod() As String
            Get
                Return ResourceManager.GetString("proc_selectserviciocod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_selectservicionombre.
        '''</summary>
        Friend ReadOnly Property proc_selectservicionombre() As String
            Get
                Return ResourceManager.GetString("proc_selectservicionombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_selectserviciosinplan.
        '''</summary>
        Friend ReadOnly Property proc_selectserviciosinplan() As String
            Get
                Return ResourceManager.GetString("proc_selectserviciosinplan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_updatecliente.
        '''</summary>
        Friend ReadOnly Property proc_updatecliente() As String
            Get
                Return ResourceManager.GetString("proc_updatecliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_updateservicio.
        '''</summary>
        Friend ReadOnly Property proc_updateservicio() As String
            Get
                Return ResourceManager.GetString("proc_updateservicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_calculocomisionporproductovendido.
        '''</summary>
        Friend ReadOnly Property procCalculoComisionPorProductoVendido() As String
            Get
                Return ResourceManager.GetString("procCalculoComisionPorProductoVendido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_cambiarcontrasenna.
        '''</summary>
        Friend ReadOnly Property procCambiarContrasenna() As String
            Get
                Return ResourceManager.GetString("procCambiarContrasenna", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_cancelarcomision.
        '''</summary>
        Friend ReadOnly Property procCancelarComision() As String
            Get
                Return ResourceManager.GetString("procCancelarComision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_calcularcomisionventasrealizadas.
        '''</summary>
        Friend ReadOnly Property procCCVentasRealizadas() As String
            Get
                Return ResourceManager.GetString("procCCVentasRealizadas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_eliminarusuario.
        '''</summary>
        Friend ReadOnly Property procDeleteCliente() As String
            Get
                Return ResourceManager.GetString("procDeleteCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_deleteplanservicio.
        '''</summary>
        Friend ReadOnly Property procdeleteplanservicio() As String
            Get
                Return ResourceManager.GetString("procdeleteplanservicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_deleteservicio.
        '''</summary>
        Friend ReadOnly Property procDeleteServicio() As String
            Get
                Return ResourceManager.GetString("procDeleteServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_insertservicio.
        '''</summary>
        Friend ReadOnly Property procInsertServicio() As String
            Get
                Return ResourceManager.GetString("procInsertServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_registrarusuario.
        '''</summary>
        Friend ReadOnly Property procInsertUsuario() As String
            Get
                Return ResourceManager.GetString("procInsertUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarmastersgerentesdisponibles.
        '''</summary>
        Friend ReadOnly Property proclistarmastersgerentesdisponibles() As String
            Get
                Return ResourceManager.GetString("proclistarmastersgerentesdisponibles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarservicios.
        '''</summary>
        Friend ReadOnly Property procListarServicios() As String
            Get
                Return ResourceManager.GetString("procListarServicios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_listarusuarios.
        '''</summary>
        Friend ReadOnly Property procListarUsuarios() As String
            Get
                Return ResourceManager.GetString("procListarUsuarios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_selectserviciocod.
        '''</summary>
        Friend ReadOnly Property procSelectServicioCod() As String
            Get
                Return ResourceManager.GetString("procSelectServicioCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_selectservicionombre.
        '''</summary>
        Friend ReadOnly Property procSelectServicioNombre() As String
            Get
                Return ResourceManager.GetString("procSelectServicioNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarusuarioid.
        '''</summary>
        Friend ReadOnly Property procSelectUsuarioId() As String
            Get
                Return ResourceManager.GetString("procSelectUsuarioId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_buscarusuarioaproxnombre.
        '''</summary>
        Friend ReadOnly Property procSelectUsuarioNombre() As String
            Get
                Return ResourceManager.GetString("procSelectUsuarioNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_updateservicio.
        '''</summary>
        Friend ReadOnly Property procUpdateServicio() As String
            Get
                Return ResourceManager.GetString("procUpdateServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to proc_modificarusuario.
        '''</summary>
        Friend ReadOnly Property procUpdateUsuario() As String
            Get
                Return ResourceManager.GetString("procUpdateUsuario", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
