'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace TipoCambioDollar
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.sdde.bccr.fi.cr", ConfigurationName:="TipoCambioDollar.wsIndicadoresEconomicosSoap")>  _
    Public Interface wsIndicadoresEconomicosSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ObtenerIndicadoresEconomicos(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicosXML", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ObtenerIndicadoresEconomicosXML(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface wsIndicadoresEconomicosSoapChannel
        Inherits TipoCambioDollar.wsIndicadoresEconomicosSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class wsIndicadoresEconomicosSoapClient
        Inherits System.ServiceModel.ClientBase(Of TipoCambioDollar.wsIndicadoresEconomicosSoap)
        Implements TipoCambioDollar.wsIndicadoresEconomicosSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtenerIndicadoresEconomicos(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Data.DataSet Implements TipoCambioDollar.wsIndicadoresEconomicosSoap.ObtenerIndicadoresEconomicos
            Return MyBase.Channel.ObtenerIndicadoresEconomicos(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles)
        End Function
        
        Public Function ObtenerIndicadoresEconomicosXML(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As String Implements TipoCambioDollar.wsIndicadoresEconomicosSoap.ObtenerIndicadoresEconomicosXML
            Return MyBase.Channel.ObtenerIndicadoresEconomicosXML(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles)
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.sdde.bccr.fi.cr", ConfigurationName:="TipoCambioDollar.wsIndicadoresEconomicosHttpGet")>  _
    Public Interface wsIndicadoresEconomicosHttpGet
        
        'CODEGEN: Generating message contract since the operation ObtenerIndicadoresEconomicos is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.sdde.bccr.fi.cr/wsIndicadoresEconomicosHttpGet/ObtenerIndicadoresEconom"& _ 
            "icosRequest", ReplyAction:="http://ws.sdde.bccr.fi.cr/wsIndicadoresEconomicosHttpGet/ObtenerIndicadoresEconom"& _ 
            "icosResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ObtenerIndicadoresEconomicos(ByVal request As TipoCambioDollar.ObtenerIndicadoresEconomicosRequest) As TipoCambioDollar.ObtenerIndicadoresEconomicosResponse
        
        'CODEGEN: Generating message contract since the operation ObtenerIndicadoresEconomicosXML is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.sdde.bccr.fi.cr/wsIndicadoresEconomicosHttpGet/ObtenerIndicadoresEconom"& _ 
            "icosXMLRequest", ReplyAction:="http://ws.sdde.bccr.fi.cr/wsIndicadoresEconomicosHttpGet/ObtenerIndicadoresEconom"& _ 
            "icosXMLResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ObtenerIndicadoresEconomicosXML(ByVal request As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLRequest) As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerIndicadoresEconomicosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public tcIndicador As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public tcFechaInicio As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public tcFechaFinal As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public tcNombre As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public tnSubNiveles As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String)
            MyBase.New
            Me.tcIndicador = tcIndicador
            Me.tcFechaInicio = tcFechaInicio
            Me.tcFechaFinal = tcFechaFinal
            Me.tcNombre = tcNombre
            Me.tnSubNiveles = tnSubNiveles
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerIndicadoresEconomicosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.sdde.bccr.fi.cr", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerIndicadoresEconomicosXMLRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public tcIndicador As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public tcFechaInicio As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public tcFechaFinal As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public tcNombre As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public tnSubNiveles As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String)
            MyBase.New
            Me.tcIndicador = tcIndicador
            Me.tcFechaInicio = tcFechaInicio
            Me.tcFechaFinal = tcFechaFinal
            Me.tcNombre = tcNombre
            Me.tnSubNiveles = tnSubNiveles
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerIndicadoresEconomicosXMLResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.sdde.bccr.fi.cr", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public [string] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [string] As String)
            MyBase.New
            Me.[string] = [string]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface wsIndicadoresEconomicosHttpGetChannel
        Inherits TipoCambioDollar.wsIndicadoresEconomicosHttpGet, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class wsIndicadoresEconomicosHttpGetClient
        Inherits System.ServiceModel.ClientBase(Of TipoCambioDollar.wsIndicadoresEconomicosHttpGet)
        Implements TipoCambioDollar.wsIndicadoresEconomicosHttpGet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TipoCambioDollar_wsIndicadoresEconomicosHttpGet_ObtenerIndicadoresEconomicos(ByVal request As TipoCambioDollar.ObtenerIndicadoresEconomicosRequest) As TipoCambioDollar.ObtenerIndicadoresEconomicosResponse Implements TipoCambioDollar.wsIndicadoresEconomicosHttpGet.ObtenerIndicadoresEconomicos
            Return MyBase.Channel.ObtenerIndicadoresEconomicos(request)
        End Function
        
        Public Function ObtenerIndicadoresEconomicos(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Data.DataSet
            Dim inValue As TipoCambioDollar.ObtenerIndicadoresEconomicosRequest = New TipoCambioDollar.ObtenerIndicadoresEconomicosRequest
            inValue.tcIndicador = tcIndicador
            inValue.tcFechaInicio = tcFechaInicio
            inValue.tcFechaFinal = tcFechaFinal
            inValue.tcNombre = tcNombre
            inValue.tnSubNiveles = tnSubNiveles
            Dim retVal As TipoCambioDollar.ObtenerIndicadoresEconomicosResponse = CType(Me,TipoCambioDollar.wsIndicadoresEconomicosHttpGet).ObtenerIndicadoresEconomicos(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TipoCambioDollar_wsIndicadoresEconomicosHttpGet_ObtenerIndicadoresEconomicosXML(ByVal request As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLRequest) As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLResponse Implements TipoCambioDollar.wsIndicadoresEconomicosHttpGet.ObtenerIndicadoresEconomicosXML
            Return MyBase.Channel.ObtenerIndicadoresEconomicosXML(request)
        End Function
        
        Public Function ObtenerIndicadoresEconomicosXML(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As String
            Dim inValue As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLRequest = New TipoCambioDollar.ObtenerIndicadoresEconomicosXMLRequest
            inValue.tcIndicador = tcIndicador
            inValue.tcFechaInicio = tcFechaInicio
            inValue.tcFechaFinal = tcFechaFinal
            inValue.tcNombre = tcNombre
            inValue.tnSubNiveles = tnSubNiveles
            Dim retVal As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLResponse = CType(Me,TipoCambioDollar.wsIndicadoresEconomicosHttpGet).ObtenerIndicadoresEconomicosXML(inValue)
            Return retVal.[string]
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.sdde.bccr.fi.cr", ConfigurationName:="TipoCambioDollar.wsIndicadoresEconomicosHttpPost")>  _
    Public Interface wsIndicadoresEconomicosHttpPost
        
        'CODEGEN: Generating message contract since the operation ObtenerIndicadoresEconomicos is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.sdde.bccr.fi.cr/wsIndicadoresEconomicosHttpPost/ObtenerIndicadoresEcono"& _ 
            "micosRequest", ReplyAction:="http://ws.sdde.bccr.fi.cr/wsIndicadoresEconomicosHttpPost/ObtenerIndicadoresEcono"& _ 
            "micosResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ObtenerIndicadoresEconomicos(ByVal request As TipoCambioDollar.ObtenerIndicadoresEconomicosRequest1) As TipoCambioDollar.ObtenerIndicadoresEconomicosResponse1
        
        'CODEGEN: Generating message contract since the operation ObtenerIndicadoresEconomicosXML is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.sdde.bccr.fi.cr/wsIndicadoresEconomicosHttpPost/ObtenerIndicadoresEcono"& _ 
            "micosXMLRequest", ReplyAction:="http://ws.sdde.bccr.fi.cr/wsIndicadoresEconomicosHttpPost/ObtenerIndicadoresEcono"& _ 
            "micosXMLResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ObtenerIndicadoresEconomicosXML(ByVal request As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLRequest1) As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLResponse1
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerIndicadoresEconomicosRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public tcIndicador As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public tcFechaInicio As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public tcFechaFinal As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public tcNombre As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public tnSubNiveles As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String)
            MyBase.New
            Me.tcIndicador = tcIndicador
            Me.tcFechaInicio = tcFechaInicio
            Me.tcFechaFinal = tcFechaFinal
            Me.tcNombre = tcNombre
            Me.tnSubNiveles = tnSubNiveles
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerIndicadoresEconomicosResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.sdde.bccr.fi.cr", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public DataSet As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DataSet As System.Data.DataSet)
            MyBase.New
            Me.DataSet = DataSet
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerIndicadoresEconomicosXMLRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public tcIndicador As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public tcFechaInicio As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public tcFechaFinal As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public tcNombre As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public tnSubNiveles As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String)
            MyBase.New
            Me.tcIndicador = tcIndicador
            Me.tcFechaInicio = tcFechaInicio
            Me.tcFechaFinal = tcFechaFinal
            Me.tcNombre = tcNombre
            Me.tnSubNiveles = tnSubNiveles
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerIndicadoresEconomicosXMLResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ws.sdde.bccr.fi.cr", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public [string] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [string] As String)
            MyBase.New
            Me.[string] = [string]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface wsIndicadoresEconomicosHttpPostChannel
        Inherits TipoCambioDollar.wsIndicadoresEconomicosHttpPost, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class wsIndicadoresEconomicosHttpPostClient
        Inherits System.ServiceModel.ClientBase(Of TipoCambioDollar.wsIndicadoresEconomicosHttpPost)
        Implements TipoCambioDollar.wsIndicadoresEconomicosHttpPost
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TipoCambioDollar_wsIndicadoresEconomicosHttpPost_ObtenerIndicadoresEconomicos(ByVal request As TipoCambioDollar.ObtenerIndicadoresEconomicosRequest1) As TipoCambioDollar.ObtenerIndicadoresEconomicosResponse1 Implements TipoCambioDollar.wsIndicadoresEconomicosHttpPost.ObtenerIndicadoresEconomicos
            Return MyBase.Channel.ObtenerIndicadoresEconomicos(request)
        End Function
        
        Public Function ObtenerIndicadoresEconomicos(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Data.DataSet
            Dim inValue As TipoCambioDollar.ObtenerIndicadoresEconomicosRequest1 = New TipoCambioDollar.ObtenerIndicadoresEconomicosRequest1
            inValue.tcIndicador = tcIndicador
            inValue.tcFechaInicio = tcFechaInicio
            inValue.tcFechaFinal = tcFechaFinal
            inValue.tcNombre = tcNombre
            inValue.tnSubNiveles = tnSubNiveles
            Dim retVal As TipoCambioDollar.ObtenerIndicadoresEconomicosResponse1 = CType(Me,TipoCambioDollar.wsIndicadoresEconomicosHttpPost).ObtenerIndicadoresEconomicos(inValue)
            Return retVal.DataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function TipoCambioDollar_wsIndicadoresEconomicosHttpPost_ObtenerIndicadoresEconomicosXML(ByVal request As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLRequest1) As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLResponse1 Implements TipoCambioDollar.wsIndicadoresEconomicosHttpPost.ObtenerIndicadoresEconomicosXML
            Return MyBase.Channel.ObtenerIndicadoresEconomicosXML(request)
        End Function
        
        Public Function ObtenerIndicadoresEconomicosXML(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As String
            Dim inValue As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLRequest1 = New TipoCambioDollar.ObtenerIndicadoresEconomicosXMLRequest1
            inValue.tcIndicador = tcIndicador
            inValue.tcFechaInicio = tcFechaInicio
            inValue.tcFechaFinal = tcFechaFinal
            inValue.tcNombre = tcNombre
            inValue.tnSubNiveles = tnSubNiveles
            Dim retVal As TipoCambioDollar.ObtenerIndicadoresEconomicosXMLResponse1 = CType(Me,TipoCambioDollar.wsIndicadoresEconomicosHttpPost).ObtenerIndicadoresEconomicosXML(inValue)
            Return retVal.[string]
        End Function
    End Class
End Namespace
